if(NOT DEFINED FEMASTER_EXECUTABLE OR NOT EXISTS "${FEMASTER_EXECUTABLE}")
    message(FATAL_ERROR "FEMASTER_EXECUTABLE must name an existing FEMaster binary")
endif()
if(NOT DEFINED FEMASTER_SOURCE_DIR)
    message(FATAL_ERROR "FEMASTER_SOURCE_DIR is required")
endif()
if(NOT DEFINED FEMASTER_TEST_DIR)
    set(FEMASTER_TEST_DIR "${CMAKE_CURRENT_BINARY_DIR}/pretension_face_pair")
endif()

file(REMOVE_RECURSE "${FEMASTER_TEST_DIR}")
file(MAKE_DIRECTORY "${FEMASTER_TEST_DIR}")
set(input "${FEMASTER_TEST_DIR}/pretension_face_pair_loadsteps.inp")
configure_file(
    "${FEMASTER_SOURCE_DIR}/tests/data/pretension_face_pair_loadsteps.inp"
    "${input}" COPYONLY)

execute_process(
    COMMAND "${FEMASTER_EXECUTABLE}" "${input}"
    RESULT_VARIABLE result
    OUTPUT_VARIABLE stdout
    ERROR_VARIABLE stderr)
set(log "${stdout}\n${stderr}")
if(NOT result EQUAL 0)
    message(FATAL_ERROR "FEMaster exited with ${result}\n${log}")
endif()
string(FIND "${log}" "[FAIL]" failure_position)
if(NOT failure_position EQUAL -1)
    message(FATAL_ERROR "Pretension regression reported a failed post-check\n${log}")
endif()
string(FIND "${log}" "split 4 shared node(s)" split_position)
if(split_position EQUAL -1)
    message(FATAL_ERROR "Merged interface nodes were not split\n${log}")
endif()

string(REGEX MATCHALL "solved mean gap = [^\r\n]+" solved_gaps "${log}")
list(LENGTH solved_gaps gap_count)
if(NOT gap_count EQUAL 3)
    message(FATAL_ERROR "Expected three solved pretension gaps, got ${gap_count}\n${log}")
endif()
list(GET solved_gaps 0 gap_1)
list(GET solved_gaps 1 gap_2)
list(GET solved_gaps 2 gap_3)
if(NOT gap_1 STREQUAL gap_2 OR NOT gap_1 STREQUAL gap_3)
    message(FATAL_ERROR "Pretension gap changed across FORCE/LOCK loadsteps: ${solved_gaps}")
endif()
string(REPLACE "solved mean gap" "locked gap" expected_lock "${gap_1}")
string(FIND "${log}" "${expected_lock}" lock_position)
if(lock_position EQUAL -1)
    message(FATAL_ERROR "Solved FORCE gap was not transferred to LOCK\n${log}")
endif()

set(result_file "${FEMASTER_TEST_DIR}/pretension_face_pair_loadsteps.res")
if(NOT EXISTS "${result_file}")
    message(FATAL_ERROR "Pretension regression did not produce a RES file")
endif()
file(READ "${result_file}" result_text)
string(FIND "${result_text}" "LC 3" third_loadcase)
if(third_loadcase EQUAL -1)
    message(FATAL_ERROR "Pretension regression did not write the third loadstep")
endif()

file(REMOVE_RECURSE "${FEMASTER_TEST_DIR}")
message(STATUS "Pretension face-pair loadstep regression PASS")
